# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from choose_he import Ui_MainWindow1

class Ui_MainWindow_xo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton_x = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_x.setGeometry(QtCore.QRect(100, 180, 80, 30))
        self.radioButton_x.setObjectName("radioButton")
        self.radioButton_x.setChecked(True)
        self.radioButton_o = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_o.setGeometry(QtCore.QRect(220, 180, 80, 30))
        self.radioButton_o.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 100, 300, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TicTacToe"))
        self.radioButton_x.setText(_translate("MainWindow", "X"))
        self.radioButton_o.setText(_translate("MainWindow", "O"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "Would you like to be X or O?"))

    def returnValue(self):
        if self.radioButton_o.isChecked():
            return "O"
        else:
            return "X"


    # def next_page(self):
    #     self.secondPage = Ui_MainWindow1()
    #     self.secondPage.setupUi(MainWindow)
    #     MainWindow.show()

    # self.secondPage.pushButton.clicked.connect(self.secondPageOpen)

    # def secondPageOpen(self):
    #     self.page = Ui_MainWindow1()
    #     self.page.setupUi(MainWindow)
    #     MainWindow.show()

# def call_function():
#     if __name__ == "__main__":
#         import sys
#         app = QtWidgets.QApplication(sys.argv)
#         MainWindow2 = QtWidgets.QMainWindow()
#         ui = Ui_MainWindow2()
#         ui.setupUi(MainWindow2)
#         MainWindow2.show()
#         sys.exit(app.exec_())
