# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from choose_he import Ui_MainWindow_he
from choose_xo import Ui_MainWindow_xo
from game import Ui_MainWindow_game


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 275, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("start_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.close_fun)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TicTacToe"))
        self.pushButton.setText(_translate("MainWindow", "Start Game"))
    
    def close_fun(self):
        self.secondPage = Ui_MainWindow_he()
        self.secondPage.setupUi(MainWindow)
        MainWindow.show()
        self.secondPage.pushButton.clicked.connect(self.secondPageOpen)

    def secondPageOpen(self):
        self.secondPage.complexity = self.secondPage.returnValue()
        self.nextpage = Ui_MainWindow_xo()
        self.nextpage.setupUi(MainWindow)
        MainWindow.show()
        self.nextpage.pushButton.clicked.connect(self.gamePageOpen)



    def gamePageOpen(self):
        self.nextpage.player = self.nextpage.returnValue()
        self.gamepage = Ui_MainWindow_game(self.secondPage.complexity,self.nextpage.player)
        self.gamepage.setupUi(MainWindow)
        MainWindow.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    